### PR TITLE
Fix failure when data compressing incompressible data

### PR DESCRIPTION
**Pull request by martint**
Incompressible data that requires more than maxCompressedLength(...)
would cause the Huffman compressor to fail with an error due to lack
of space in the output buffer.

With this change, when that happens, the compressor will fall back
to emitting the raw literals instead.

Fixes https://github.com/airlift/aircompressor/issues/122

### CODE REVIEW

**Review by dain — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
It's great to have this. May I ask when is the next release with this?

**Comment by martint** [comment]
The release is in progress. It should be available in maven central soon.

**Comment by dongjoon-hyun** [comment]
Thank you so much!

**Comment by martint** [comment]
@dongjoon-hyun, release 0.21 is now available in maven central. Please let me know if you encounter any issues.

**Comment by dongjoon-hyun** [comment]
Thanks. Yeps, for Apache ORC, it's tested and merged via https://issues.apache.org/jira/browse/ORC-965 .
I guess @melin can test it more on his Spark jobs (the initial reported one), too.

**Pull request merged**
